theme: jekyll-theme-minimal
title: Gary Pang, Software Engineer
description: Gary Pang is a software engineer experienced in building applications with JavaScript (ES6+), Angular, React, Node.js and Express. 
